---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-service-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: spoon-radio/nginx-service
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:choiseockjun/spoon_radio.git
    targetRevision: main
    path: dev/nginx-service
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true